# build version format
version: "{build}"

# fix lineendings in Windows
init:
  - git config --global core.autocrlf input

# environments to test on
environment:
  matrix:
    - nodejs_version: 0.10

# get latest stable version of nodejs
# install dependencies
install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)
  - npm install

build: off

test_script:
  - node --version
  - npm --version
  - ps: npm test
  - cmd: npm test
